In [1]:
import numpy as np

In [2]:
docs = ['(My) name is Ritesh u can call me bittu',
        'i also have interestes',
        'Currently live in varanasi',
        'favourite thing is technology',
        'i also like to play cricket',
        'i loves cars and bike also ',
        'also learning new things',
        'mclaren is my favourite car',
        'h2 is favourite',
        'I like old honey singh song']

⭐**Tokenizer a tool that breaks raw text into smaller pieces called tokens, like words, parts of words, or characters, and translates them into numbers that a computer can understand**

 **"AI is fun!"  Tokens: ["AI", "is", "fun", "!"]**


In [3]:
import keras
from keras.layers import TextVectorization # tokenizer only thing is to break the text into smaller piece that it
#it donot change into the integer here and ther is combined menthod with it ouput_mode = int it it integer encoding

tokenizer = TextVectorization(output_mode='int')


In [4]:
tokenizer.adapt(docs) # like tokenizer.fit_on_text(docs) with the old tuturial but removed

In [5]:
word_after_tokenizer= tokenizer.get_vocabulary()
print(word_after_tokenizer)

['', '[UNK]', np.str_('is'), np.str_('i'), np.str_('also'), np.str_('favourite'), np.str_('my'), np.str_('like'), np.str_('varanasi'), np.str_('u'), np.str_('to'), np.str_('things'), np.str_('thing'), np.str_('technology'), np.str_('song'), np.str_('singh'), np.str_('ritesh'), np.str_('play'), np.str_('old'), np.str_('new'), np.str_('name'), np.str_('me'), np.str_('mclaren'), np.str_('loves'), np.str_('live'), np.str_('learning'), np.str_('interestes'), np.str_('in'), np.str_('honey'), np.str_('have'), np.str_('h2'), np.str_('currently'), np.str_('cricket'), np.str_('cars'), np.str_('car'), np.str_('can'), np.str_('call'), np.str_('bittu'), np.str_('bike'), np.str_('and')]


In [6]:
vocab = tokenizer.get_vocabulary() #[UNK]in output: Unknown It is a special token used when the model encounters a word that was not present in the vocabulary during adapt().
                                    # index 0 is reserved for padding so that vector of text is same
for index, word in enumerate(word_after_tokenizer):
    print(index, "→", word)

0 → 
1 → [UNK]
2 → is
3 → i
4 → also
5 → favourite
6 → my
7 → like
8 → varanasi
9 → u
10 → to
11 → things
12 → thing
13 → technology
14 → song
15 → singh
16 → ritesh
17 → play
18 → old
19 → new
20 → name
21 → me
22 → mclaren
23 → loves
24 → live
25 → learning
26 → interestes
27 → in
28 → honey
29 → have
30 → h2
31 → currently
32 → cricket
33 → cars
34 → car
35 → can
36 → call
37 → bittu
38 → bike
39 → and


In [7]:
  # u can see here all unique word make capital small removed the special character

In [8]:
tokenizer(docs) # all text into the integer with proper padding and now all have same length
# index 0 is reserved for padding so that vector of text is same and  index 1 for the unknown  , u can match all vector

<tf.Tensor: shape=(10, 9), dtype=int64, numpy=
array([[ 6, 20,  2, 16,  9, 35, 36, 21, 37],
       [ 3,  4, 29, 26,  0,  0,  0,  0,  0],
       [31, 24, 27,  8,  0,  0,  0,  0,  0],
       [ 5, 12,  2, 13,  0,  0,  0,  0,  0],
       [ 3,  4,  7, 10, 17, 32,  0,  0,  0],
       [ 3, 23, 33, 39, 38,  4,  0,  0,  0],
       [ 4, 25, 19, 11,  0,  0,  0,  0,  0],
       [22,  2,  6,  5, 34,  0,  0,  0,  0],
       [30,  2,  5,  0,  0,  0,  0,  0,  0],
       [ 3,  7, 18, 28, 15, 14,  0,  0,  0]])>

In [9]:
tokenizer.vocabulary_size() #40 vocabulary entries, of which 38 are actual words if the two standard special entries are present.

40

#Lets now work on new dataset like imdb review on movie ,means sentiments training

In [10]:
from keras.datasets import imdb
from keras.layers import Dense,SimpleRNN,Flatten
from keras import Sequential

In [11]:
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [12]:
x_train.shape # These are tokenized and converted into the integer u can say that integer encoded

(25000,)

In [13]:
x_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [14]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

Length of the review in not same so we have to include the zero padding

In [15]:
len(x_train[1])

189

In [16]:
len(x_train[2])

141

In [17]:
max(len(x) for x in x_train) # this is maximum word sentence review

2494

In [18]:
from keras.utils import  pad_sequences

x_train = pad_sequences(x_train,padding='post')# maxlen=4  sets the maximum/fixed sequence length to 4. if u have 5 word the
                                                          # then one word is removed so set the maximun so review word cannot delete also
                                                          #set max = 5000 also make the sentence add zero padding .
x_test = pad_sequences(x_test,padding='post')# max_len basically means trimming the word


In [19]:
len(x_train[1])

2494

In [20]:
len(x_train[2])

2494

In [21]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(2494,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'])

In [23]:
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 113s 141ms/step - accuracy: 0.5026 - loss: 0.6939 - val_accuracy: 0.5017 - val_loss: 0.6933
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 107s 137ms/step - accuracy: 0.5008 - loss: 0.6944 - val_accuracy: 0.5029 - val_loss: 0.6947
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 142s 137ms/step - accuracy: 0.4929 - loss: 0.6940 - val_accuracy: 0.5029 - val_loss: 0.6936
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 106s 136ms/step - accuracy: 0.4959 - loss: 0.6941 - val_accuracy: 0.5029 - val_loss: 0.6941
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 107s 137ms/step - accuracy: 0.5029 - loss: 0.6937 - val_accuracy: 0.5000 - val_loss: 0.6932
