In [1]:
docs = ['(My) name is Ritesh u can call me bittu',
        'i also have interestes',
        'Currently live in varanasi',
        'favourite thing is technology',
        'i also like to play cricket',
        'i loves cars and bike also ',
        'also learning new things',
        'mclaren is my favourite car',
        'h2 is favourite',
        'I like old honey singh song']

#Tokenization and Integer Encoding

In [2]:
import keras
from keras.layers import TextVectorization # tokenizer only thing is to break the text into smaller piece that it
#it donot change into the integer here and ther is combined menthod with it ouput_mode = int it it integer encoding

tokenizer = TextVectorization(output_mode='int')


In [3]:
tokenizer.adapt(docs) # like tokenizer.fit_on_text(docs) with the old tuturial but removed
# it also do automatically padding so u saw many zeroes in tokenizer(docs)output

In [4]:
word_after_tokenizer= tokenizer.get_vocabulary()
print(word_after_tokenizer)

['', '[UNK]', np.str_('is'), np.str_('i'), np.str_('also'), np.str_('favourite'), np.str_('my'), np.str_('like'), np.str_('varanasi'), np.str_('u'), np.str_('to'), np.str_('things'), np.str_('thing'), np.str_('technology'), np.str_('song'), np.str_('singh'), np.str_('ritesh'), np.str_('play'), np.str_('old'), np.str_('new'), np.str_('name'), np.str_('me'), np.str_('mclaren'), np.str_('loves'), np.str_('live'), np.str_('learning'), np.str_('interestes'), np.str_('in'), np.str_('honey'), np.str_('have'), np.str_('h2'), np.str_('currently'), np.str_('cricket'), np.str_('cars'), np.str_('car'), np.str_('can'), np.str_('call'), np.str_('bittu'), np.str_('bike'), np.str_('and')]


In [5]:
sequence = tokenizer(docs)
print(sequence)

tf.Tensor(
[[ 6 20  2 16  9 35 36 21 37]
 [ 3  4 29 26  0  0  0  0  0]
 [31 24 27  8  0  0  0  0  0]
 [ 5 12  2 13  0  0  0  0  0]
 [ 3  4  7 10 17 32  0  0  0]
 [ 3 23 33 39 38  4  0  0  0]
 [ 4 25 19 11  0  0  0  0  0]
 [22  2  6  5 34  0  0  0  0]
 [30  2  5  0  0  0  0  0  0]
 [ 3  7 18 28 15 14  0  0  0]], shape=(10, 9), dtype=int64)


In [6]:
tokenizer.get_vocabulary()

['',
 '[UNK]',
 np.str_('is'),
 np.str_('i'),
 np.str_('also'),
 np.str_('favourite'),
 np.str_('my'),
 np.str_('like'),
 np.str_('varanasi'),
 np.str_('u'),
 np.str_('to'),
 np.str_('things'),
 np.str_('thing'),
 np.str_('technology'),
 np.str_('song'),
 np.str_('singh'),
 np.str_('ritesh'),
 np.str_('play'),
 np.str_('old'),
 np.str_('new'),
 np.str_('name'),
 np.str_('me'),
 np.str_('mclaren'),
 np.str_('loves'),
 np.str_('live'),
 np.str_('learning'),
 np.str_('interestes'),
 np.str_('in'),
 np.str_('honey'),
 np.str_('have'),
 np.str_('h2'),
 np.str_('currently'),
 np.str_('cricket'),
 np.str_('cars'),
 np.str_('car'),
 np.str_('can'),
 np.str_('call'),
 np.str_('bittu'),
 np.str_('bike'),
 np.str_('and')]

In [7]:
tokenizer.vocabulary_size() #unique words

40

#Embedding

In [8]:
from keras import Sequential
from keras.layers import Embedding,Dense,Input

output_dim=4(hyperpramter) 2D/3D/4D is simply the number of coordinates used to locate each token in the embedding space. The larger the dimension, the more numerical capacity the representation has, although higher dimension does not automatically mean a better embedding.

Input(shape=9) means highest sencentence word

1st u have to write the unique vocabulary like 40 unique word get by tokenizer.

In [9]:
model = Sequential()
model.add(Input(shape=(9,)))
model.add(Embedding(40,output_dim=4))
#ouput_dim each token gets a vector containing 4 numbers
#output_dim determines the dimensionality of the embedding space. Similarity between tokens can then be measured using their vectors in that space.

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 9, 4)           │           160 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 160 (640.00 B)

 Trainable params: 160 (640.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile('adam','accuracy')

# This is Embedding first we do the integer Encoding then Embedding

 for every word we get 4 words [ 0.03391692  0.0376677  -0.03837267 -0.02630422]

 when we have set the output dim 4 then we get the 4 dimesion for each word [ 0.03391692  0.0376677  -0.03837267 -0.02630422] like this

In [ ]:
pred = model.predict(sequence)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[[ 0.03137294  0.04800342 -0.01575118  0.03935002]
  [-0.00982283  0.0259066  -0.04863379 -0.04558766]
  [-0.04886479  0.04279018  0.0054737   0.02743672]
  [-0.03617429  0.02644842  0.01927307  0.00303228]
  [-0.03773911  0.02326846 -0.03651923  0.00318452]
  [-0.027159    0.01889506  0.02881256  0.0380716 ]
  [ 0.0344332  -0.02516128  0.01299748  0.04794696]
  [-0.01344725 -0.04724629  0.01229272  0.01975325]
  [-0.04847652 -0.01798999 -0.00021575  0.0289625 ]]

 [[-0.00064478  0.03040979  0.00451015  0.00627192]
  [-0.02850244 -0.00620203 -0.03069948 -0.04699973]
  [-0.04286728  0.01441154 -0.00629711 -0.04111926]
  [-0.00928929 -0.04674352 -0.02190056  0.01538039]
  [-0.00755804  0.03800618  0.01476956 -0.00632976]
  [-0.00755804  0.03800618  0.01476956 -0.00632976]
  [-0.00755804  0.03800618  0.01476956 -0.00632976]
  [-0.00755804  0.03800618  0.01476956 -0.00632976]
  [-0.00755804  0.03800618  0.01476956 -0.00632976]]

 [[ 0.0201639  -0.032413

# Lets try on imbd dataset

In [13]:
from keras import Sequential
from keras.layers import Flatten,Embedding,SimpleRNN,Dense

In [14]:
from os import X_OK
from keras.datasets import imdb


In [15]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Before padding → different sequence lengths → no fixed second dimension.so not columns given

In [16]:
x_train.shape

(25000,)

The review has all different sentence so we do the padding

In [17]:
from keras.utils import pad_sequences
x_train = pad_sequences(x_train,padding='post')
x_test = pad_sequences(x_test,padding='post')


In [18]:
x_train.shape # each row contained 2494 items

(25000, 2494)

In [19]:
print(x_train.max()) # maximun totol number of ids create  with the integer encoding

88586


#Embedding

10000 means 100 unique tokens in the vocabulary (more precisely, 10000 token IDs the layer can look up).

Vocabulary
──────────────

0 → PADDING

1 → UNKNOWN Words

2 → I

3 → Love

4 → apple

...

99 → banana


2494 = 2494 numbers for each token's embedding vector(each embeddding vector item)

In [ ]:
model = Sequential()

model.add(Input(shape=(2494,))) #input shape
model.add(Embedding(input_dim = 88587,output_dim=2))#ouput_dim(hyperparameter)
#88587 vocabulary size , unique token and 2d dimension space totol number of ids with the integer encoding
#i donot know the exactly unique so i set it to 10000

model.add(SimpleRNN(32,return_sequences=False))# loop traning of 32

model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 2494, 2)        │       177,174 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 178,327 (696.59 KB)

 Trainable params: 178,327 (696.59 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 141s 177ms/step - accuracy: 0.4990 - loss: 0.6949 - val_accuracy: 0.5000 - val_loss: 0.6934
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 137s 172ms/step - accuracy: 0.4979 - loss: 0.6936 - val_accuracy: 0.4991 - val_loss: 0.6935
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 134s 171ms/step - accuracy: 0.5004 - loss: 0.6936 - val_accuracy: 0.4991 - val_loss: 0.6945
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 133s 171ms/step - accuracy: 0.4982 - loss: 0.6938 - val_accuracy: 0.4996 - val_loss: 0.6947
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 135s 172ms/step - accuracy: 0.4972 - loss: 0.6939 - val_accuracy: 0.5000 - val_loss: 0.6932
